services:
  sensor_portal_nginx:
      build: 
          context: .
          dockerfile: ./dockerfiles/sensor_portal_nginx.dockerfile
      ports:
          - "8080:80"
          depends_on:
            sensor_portal_django:
              condition: service_healthy
              restart: true
            sensor_portal_frontend:
              restart: true
      restart: unless-stopped
      volumes:      
        - ./file_storage:/file_storage
        - ./sensor_portal/static:/backend_static  
  sensor_portal_frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/sensor_portal_frontend.dockerfile
    image: sensor_portal_frontend_image
    ports:
      - '3000'
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    command: npm start
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_BASE_URL=api
  sensor_portal_django:
    build:
      context: .
      dockerfile: ./dockerfiles/sensor_portal_django.dockerfile
    image: sensor_portal_django_image
    command: bash -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./file_storage:/media/file_storage
      - ./sensor_portal:/usr/src/sensor_portal
    ports:
      - "8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://sensor_portal_redis:6379/0
      - CELERY_BACKEND=redis://sensor_portal_redis:6379/0
      - DEV=True
      - FIELD_ENCRYPTION_KEY=FrMHRMwLSdQytSjWRAIwaFPzzWC1R5XIPaH6HQbcryA=
    depends_on:
      sensor_portal_db:
        condition: service_healthy
        restart: true
      sensor_portal_redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/api || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 5
    restart: always
  sensor_portal_worker:
    image: sensor_portal_django_image
    command: bash -c "celery -A sensor_portal worker --autoscale 10,1 --loglevel=INFO -Q main_worker"
    volumes:
      - ./file_storage:/media/file_storage
      - ./sensor_portal:/usr/src/sensor_portal
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://sensor_portal_redis:6379/0
      - CELERY_BACKEND=redis://sensor_portal_redis:6379/0
      - DEV=True
      - FIELD_ENCRYPTION_KEY=FrMHRMwLSdQytSjWRAIwaFPzzWC1R5XIPaH6HQbcryA=
    depends_on:
      sensor_portal_db:
        condition: service_healthy
        restart: true
      sensor_portal_redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 
    restart: always
  sensor_portal_single_worker:
    image: sensor_portal_django_image
    command: bash -c "celery -A sensor_portal worker -c 1 --loglevel=INFO -Q single_worker"
    volumes:
      - ./file_storage:/media/file_storage
      - ./sensor_portal:/usr/src/sensor_portal
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://sensor_portal_redis:6379/0
      - CELERY_BACKEND=redis://sensor_portal_redis:6379/0
      - DEV=True
      - FIELD_ENCRYPTION_KEY=FrMHRMwLSdQytSjWRAIwaFPzzWC1R5XIPaH6HQbcryA=
    depends_on:
      sensor_portal_db:
        condition: service_healthy
        restart: true
      sensor_portal_redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s    
    restart: always
  sensor_portal_beat:
    image: sensor_portal_django_image
    command: bash -c "celery -A sensor_portal beat --loglevel=INFO"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://sensor_portal_redis:6379/0
      - CELERY_BACKEND=redis://sensor_portal_redis:6379/0
      - DEV=True
      - FIELD_ENCRYPTION_KEY=FrMHRMwLSdQytSjWRAIwaFPzzWC1R5XIPaH6HQbcryA=
    depends_on:
      sensor_portal_db:
        condition: service_healthy
        restart: true
      sensor_portal_redis:
        condition: service_healthy
        restart: true
    volumes:
      - ./sensor_portal:/usr/src/sensor_portal
    restart: always
  sensor_portal_db:
    image: postgis/postgis:14-3.3
    volumes:
      - ./sensor_portal_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 100
      start_period: 80s 
    restart: always
  sensor_portal_redis:
      image: "redis:alpine"
      healthcheck:
        test: [ "CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 60s
        retries: 100
        start_period: 80s    
      restart: always
volumes:
  file_storage:
  sensor_portal_database:
